### ISSUE TITLE
when robot's movement is cancel they shot

### ISSUE THREAD

**Issue by juanjosegzl** [juanjosegzl/learningpygame#26]
so if two robot keep colliding they keep shoting creating a large line of lasers

I suppose this happens because the robot tries to move in the direction which is block, the new movement is canceled, it passes to the new state and shots, and again and again

we can modify, random_position to discard moving to the spot where there is another robot

...but, yeah, what if the robot is block in all sides :S

**Comment by hugoaguirre** [comment]
So the robot starts shooting immediately it gets assigned a new position to move?
If that so, you could add a 'delay' (or so) in order to shoot only when certain conditions are met, for example: each odd movement assignment.
